# Generated by Django 4.2.2 on 2023-06-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealelement',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='mealelement',
            old_name='product_id',
            new_name='product',
        ),
    ]
