# Generated by Django 4.2.2 on 2023-06-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_rename_meal_id_mealelement_meal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='creator_user_id',
            new_name='creator_user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='creator_user_id',
            new_name='creator_user',
        ),
    ]
