# Generated by Django 4.2.2 on 2023-06-18 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0003_rename_creator_user_id_meal_creator_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
