# Generated by Django 4.2.2 on 2023-06-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meal_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
