# Generated by Django 4.2.2 on 2023-06-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_meal_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.AlterField(
            model_name='mealelement',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
